In [40]:
# Import necessary libraries

import numpy as np
import pandas as pd
import faker
from faker import Faker
from faker.providers import misc, date_time, address
import random
from faker.providers import internet
import warnings

# Ignore any warnings that might come up during the execution of the script.

warnings.filterwarnings('ignore')

In [41]:
# Initialize a Faker instance

fake = Faker()

In [42]:
# Generate a list of 100 unique order IDs using a custom format

order_ids = [fake.bothify(text = '????####', letters = 'ABCDE') for _ in range(100)]

# Generate a list of 100 dates between January 1, 2022 and April 10, 2022

order_dates = pd.date_range(start = "2022-01-01", end = "2022-04-10", periods = 100)

# Generate a list of 100 fake customer names

customers = [fake.name() for _ in range(100)]

# Generate a list of 100 regions, randomly choosing between 'East', 'West', 'North', and 'South'

regions = [fake.random_element(elements = ('East','West','North','South')) for _ in range(100)]

# Create a list of 100 'Grocery' category labels

categories = ['Grocery' for _ in range(100)]

# Generate a list of 100 subcategories, randomly choosing between 'Bakery', 'Canned Goods', 'Dairy', and 'Produce'

subcategories = [fake.random_element(elements = ('Bakery','Canned Goods','Dairy','Produce'))for _ in range(100)]

# Predefined list of grocery-related words

grocery_words = ['break','milk','cheese','eggs','butter','flour','suger','rice','pasta']

# Generate a list of 100 products, randomly choosing from the predefined list

product = [fake.random_element(elements = grocery_words) for _ in range(100)]

# Generate a list of 100 sales amounts, each a random float between 500 and 10000

sales = [round(random.uniform(500,10000),2) for _ in range(100)]

# Generate a list of 100 profit amounts, each a random float between 50 and 2000

profit = [round(random.uniform(50,2000),2) for _ in range(100)]

# Generate a list of 100 quantities, each a random integer between 1 and 20

quantity = [random.randint(1,20) for _ in range(100)]

In [43]:
# Create a dictionary of the generated data

data = {"Order_ID" : order_ids,
        'Order_Date': order_dates,
        'Customer':customers,
        'Region': regions,
        'Category':categories,'Sub_Category':subcategories,"Product":product,
        'Sales':sales,"Profit":profit,"Quantity":quantity}

In [44]:
# Convert the dictionary to a pandas DataFrame

df = pd.DataFrame(data)

In [45]:
df.head()

,Order_ID,Order_Date,Customer,Region,Category,Sub_Category,Product,Sales,Profit,Quantity
0,AEDA8557,2022-01-01,Kimberly Chavez,East,Grocery,Produce,flour,9292.64,1248.82,3
1,DEAC0991,2022-01-02,Angelica Ellison,West,Grocery,Bakery,cheese,1914.46,1818.28,11
2,BEDB4685,2022-01-03,Tamara Duke,West,Grocery,Bakery,pasta,7170.26,1020.10,2
3,ADAA4394,2022-01-04,Carly Woods,South,Grocery,Bakery,flour,7327.86,768.79,10
4,DCDD6438,2022-01-05,Julia Curry,West,Grocery,Dairy,suger,9608.36,179.86,11